#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source "$SCRIPT_DIR/lib/theme"


dg_config (){
    if [[ $# -eq 0 ]]; then
        config
    fi

    if [[ $1 == "help" ]]; then
        config_help
    fi

    while [[ $# -ne 0 ]]; do
        if [[ $# -lt 2 ]]; then
            invalid_config;
        fi
        case $1 in
            "criteria") shift; 
                if [[ $1 == "month" || $1 == "type" ]]; then
                    set_criteria $1
                else
                    invalid_config
                fi
            ;;
            "nested") shift; 
                if [[ $1 == "type" || $1 == "month" ]]; then
                    set_nested $1
                else
                    invalid_config
                fi
            ;;
            "duplicates") shift;
                if [[ $1 == "overwrite" || $1 == "rename" ]]; then
                    set_dups $1;
                else
                    invalid_config
                fi
            ;;
            *) invalid_config ;;
        esac
        shift;
    done

}

invalid_config() {
    echo -e "$RED""Invalid configuration data. Please refer to the documentation.$REGULAR";
    echo -e "Or try running $BOLD$0 config help$REGULAR"
    exit 1;
}

config_help() {
    echo "Hello"
    exit 0
}

config() {
    echo "Nothin here!"
}

# Individual config functions

set_criteria(){
    criteria=$(cat ~/.config/downganizer.conf | grep -m 1 "CRITERIA=" | cut -d '=' -f2)
    if [[ $1 == "$criteria" ]]; then
        return;
    fi

    nested=$(cat ~/.config/downganizer.conf | grep -m 1 "NESTED_CRITERIA=" | cut -d '=' -f2)
    if [[ "$nested" == "$1" ]]; then
        sed -i 's/NESTED=true/NESTED=false/' ~/.config/downganizer.conf
        sed -i "s/NESTED_CRITERIA=$nested/NESTED_CRITERIA=null/" ~/.config/downganizer.conf
    fi

    sed -i "s/CRITERIA=$criteria/CRITERIA=$1/" ~/.config/downganizer.conf
}

set_nested(){
    echo "Hello"
}

set_dups() {
    dup=$(cat ~/.config/downganizer.conf | grep -m 1 "DUPLICATES=" | cut -d '=' -f2)
    if [[ "$dup" == "$1" ]]; then
        return;
    fi

    sed -i "s/DUPLICATES=$dup/DUPLICATES=$1/" ~/.config/downganizer.conf
}

