#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
LIB_DIR="/usr/share/downganizer/lib"

PROD=false

if [[ "$PROD" = false ]]; then
    LIB_DIR=$(echo "$SCRIPT_DIR" | sed 's/\/lib$//')/lib
fi

source "$LIB_DIR/theme"
source "$LIB_DIR/utils"
source "$LIB_DIR/downganize"

inotifywait -m ~/Downloads -e create -e moved_to 2>/dev/null|
while read -r directory event file; do
    if [ -d "$HOME/Downloads/$file" ]; then
        continue
    fi
    siz=$(stat -c %s "$HOME/Downloads/$file")
    if [ -z "$siz"] || [ "$siz" -eq 0 ]; then
        sleep 0.5
        siz=$(stat -c %s "$HOME/Downloads/$file")
        if [ -z "$siz" ] || [ "$siz" -eq 0 ]; then
            continue
        fi
    fi
    dest=$(sort_file "$HOME/Downloads/$file")
    if [[ -n "$dest" ]]; then
        new_file=$(basename "$file")
        dups=$(get_config "DUPLICATES")
        if [[ "$dups" == "rename" ]]; then
            new_file=$(rename_file "$dest/$(basename "$file")")
        fi
        mv -f "$HOME/Downloads/$file" "$dest/$new_file"
    fi
done 2>/dev/null