#!/bin/bash

get_config(){
	conf="$1"
	val=$(cat ~/.config/downganizer.conf | grep -m 1 "$conf=" | cut -d '=' -f2)
	echo $val
}

get_conf_options(){
	conf="$1"
	val=$(cat /etc/downganizer/options.conf | grep -m 1 "$conf=" | cut -d '=' -f2 | sed 's/\[//' | sed 's/\]//' )
	val=($val)
	echo ${val[@]}
}

rename_file(){
    if [[ -e "$1" ]]; then
        base=$(basename "$1")
        dir=$(dirname "$1")
        name="${base%.*}"
        ext="${base##*.}"
        count=1
        new_name="$name-$count.$ext"
        while [[ -e "$dir/$new_name" ]]; do
            ((count++))
            new_name="$name-$count.$ext"
        done
        echo "$new_name"
    else
        base=$(basename "$1")
        echo "$base"
    fi
}
